# NumPy Tutorial

Shouvik Mani <br>
September 24, 2021 <br>
COMS 4995: Applied Machine Learning, Columbia University

In [1]:
import numpy as np

### 1. Creating Vectors and Matrices

Create a vector.

In [2]:
x = np.array([1, 2, 3, 4, 5])

print(x.shape)
print(x)

(5,)
[1 2 3 4 5]


Create a matrix.

In [3]:
A = np.array([[2, 1, 4], 
              [5, 0, 1], 
              [3, 2, 1]])
              
print(A.shape)
print(A)

(3, 3)
[[2 1 4]
 [5 0 1]
 [3 2 1]]


Special matrices

In [4]:
np.zeros(shape=(3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones(shape=(4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# Identity matrix
np.eye(N=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Evenly spaced numbers

In [7]:
# 11 numbers between 0 and 1
x = np.linspace(start=0, stop=1, num=11)

print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


Sample random numbers from a Normal distribution. There are many more distributions you can choose from (see documentation for np.random).

In [8]:
# Seed the random number generator (important for reproducible results)
np.random.seed(0)
x = np.random.normal(loc=0, scale=5, size=5)

print(x)

[ 8.82026173  2.00078604  4.89368992 11.204466    9.33778995]


### 2. Indexing, Slicing, and Iterating

In [9]:
A = np.array([[2, 1, 4], 
              [5, 0, 1], 
              [3, 2, 1]])

Access an element by index

In [10]:
A[2]   # First index is the row (2)

array([3, 2, 1])

In [11]:
A[2, 2]   # First index is row, second index is col

1

Set a value at an index

In [12]:
A[2, 2] = -1
print(A)

[[ 2  1  4]
 [ 5  0  1]
 [ 3  2 -1]]


Slicing

In [13]:
# Slice rows 1 through 2, cols 1 through 2
A[1:, 1:]

array([[ 0,  1],
       [ 2, -1]])

In [14]:
# Slice all rows, col 0
A[:, 0]

array([2, 5, 3])

Iterating over a matrix

In [15]:
# Iterating over rows
for row in A:
    print(row)

[2 1 4]
[5 0 1]
[ 3  2 -1]


In [16]:
sum = 0

# Iterating over rows and cols
for row in A:
    for elem in row:
        sum += elem
        
print(sum)

17


### 3. Basic Vector and Matrix Operations

Scalar multiplication and vector addition

In [17]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 0, 1, 0, 1])

print(2 * x + y)

[ 3  4  7  8 11]


Dot product

In [18]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 0, 1, 0, 1])

# Two different ways!
print(x @ y)
print(x.dot(y))

9
9


Vector norm

In [19]:
x = np.array([1, 2, 3, 4, 5])

print(np.linalg.norm(x, 1))   # L1-norm
print(np.linalg.norm(x, 2))   # L2-norm (i.e. vector magnitude)

15.0
7.416198487095663


Matrix transpose

In [20]:
A = np.array([[2, 1, 4], 
              [5, 0, 1], 
              [3, 2, 1]])

print(A.T)

[[2 5 3]
 [1 0 2]
 [4 1 1]]


Reshape a matrix

In [21]:
A = np.array([[2, 1, 4], 
              [5, 0, 1]])
a = A.reshape((6, 1))

print(a)

[[2]
 [1]
 [4]
 [5]
 [0]
 [1]]


Scalar multiplication and matrix addition

In [22]:
A = np.array([[2, 1, 4], 
              [5, 0, 1], 
              [3, 2, 1]])
B = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

print(2 * A + B)

[[ 5  4 11]
 [14  5  8]
 [13 12 11]]


Elementwise multiplication (**not matrix multiplication**)

In [23]:
print(A * B)

[[ 2  2 12]
 [20  0  6]
 [21 16  9]]


Matrix multiplication

In [24]:
# Two different ways!
print(A @ B)
print()
print(A.dot(B))

[[34 41 48]
 [12 18 24]
 [18 24 30]]

[[34 41 48]
 [12 18 24]
 [18 24 30]]


Matrix inverse

In [25]:
A = np.array([[3, 1], 
              [1, 3]])
A_inv = np.linalg.inv(A)

print(A_inv)

[[ 0.375 -0.125]
 [-0.125  0.375]]


In [26]:
A @ A_inv

array([[1., 0.],
       [0., 1.]])

Stacking matrices

In [27]:
A = np.array([[2, 1, 4], 
              [5, 0, 1]])
B = np.array([[1, 2, 3], 
              [4, 5, 6]])

In [28]:
np.hstack([A, B])

array([[2, 1, 4, 1, 2, 3],
       [5, 0, 1, 4, 5, 6]])

In [29]:
np.vstack([A, B])

array([[2, 1, 4],
       [5, 0, 1],
       [1, 2, 3],
       [4, 5, 6]])

Element-wise functions (e.g. np.log, np.exp, np.sqrt)

In [30]:
A = np.array([[1, 4, 9], 
              [16, 25, 36], 
              [49, 64, 81]])

np.sqrt(A)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

Aggregate functions (e.g. np.mean, np.std, np.sum)

In [31]:
A = np.array([[1, 1, 1], 
              [2, 2, 2], 
              [3, 3, 3]])

print(A.sum())          # Sum of all elements in A
print(A.sum(axis=0))    # Sum of each column in A
print(A.sum(axis=1))    # Sum of each row in A

18
[6 6 6]
[3 6 9]


### 4. Solving Systems of Linear Equations

Consider the following system of linear equations:

$$
\begin{aligned}
3a + b &= 5 \\
a - 5b &= 7
\end{aligned}
$$

We can rewrite this as the equation $A x = b$, where $A$ and $b$ are defined as follows.

In [33]:
A = np.array([[3, 1], [1, -5]])
b = np.array([5, 7])

Then, we can solve for an exact solution $x$.

In [34]:
# Find an exact solution x for A x = b
x = np.linalg.solve(A, b)
x

array([ 2., -1.])

This is the same as $x = A^{-1} b$. But `np.linalg.solve(A, b)` is the preferred method.

In [35]:
x = np.linalg.inv(A) @ b
x

array([ 2., -1.])

What happens when $A$ is not a square matrix? For example, consider the following 
(overdetermined) system of linear equations:

$$
\begin{aligned}
3a + b &= 5 \\
a - 5b &= 7 \\
a + b &= 0
\end{aligned}
$$


In [36]:
A = np.array([[3, 1], [1, -5], [1, 1]])
b = np.array([5, 7, 0])

We can't use `np.linalg.solve(A, b)` since A is not square, i.e. not invertible.

In [37]:
# Does not work - A not invertible
x = np.linalg.solve(A, b)
x

LinAlgError: Last 2 dimensions of the array must be square

Instead, we can find a least squares approximate solution for $x$.

In [38]:
# Find an approximate solution x for A x = b using least squares.
x, resid, rank, s = np.linalg.lstsq(A, b)
x

<ipython-input-38-a23de93341b9>:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, resid, rank, s = np.linalg.lstsq(A, b)


array([ 1.90540541, -1.04054054])

Estimates for $b$ using least squares approx. for $x$.

In [41]:
A @ x

array([4.67567568, 7.10810811, 0.86486486])

In [42]:
b

array([5, 7, 0])

### 5. Broadcasting

Consider the following matrix $A$.

In [43]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])

print(A)

[[1 2 3]
 [4 5 6]]


Imagine that you want to add 2 to each element of the matrix above. One way to do it is the following.

In [44]:
B = np.array([[2, 2, 2], 
              [2, 2, 2]])

A + B

array([[3, 4, 5],
       [6, 7, 8]])

However, a cleaner way to write this would be to simply do `A + 2`. This is a NumPy feature known as **broadcasting**, which automatically resizes arrays in the most natural way to perform an operation.

In [45]:
A + 2

array([[3, 4, 5],
       [6, 7, 8]])

Broadcasting can be applied in interesting ways. Here, we subtract off the mean from each column of A. This works even though A has dimension (2, 3) and the means have dimension (3,).

In [47]:
means = A.mean(axis=0)
means

array([2.5, 3.5, 4.5])

In [48]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
print("Dimension of A:", A.shape)
print("Dimension of means:", means.shape)

A - means

Dimension of A: (2, 3)
Dimension of means: (3,)


array([[-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5]])

### 6. Vectorization

One of the key principles when using NumPy is to *vectorize your code*. Vectorizing your code means to favor matrix/vector operations over for-loops. Vectorizing code has two main benefits:
- Vectorized code uses optimized NumPy operations, which makes it faster.
- Vectorized code is cleaner and easier to read than code with for-loops.

Next, we consider two examples of writing vectorized code.

### Example 1: Standardization

Transform the matrix $X$ so that each column is scaled to have a mean of 0 and variance of 1.

In [50]:
X = np.random.normal(loc=10, scale=5, size=(1000000, 5))
print(X.shape)
X

(1000000, 5)


array([[ 5.1136106 , 14.75044209,  9.24321396,  9.48390574, 12.05299251],
       [10.72021786, 17.27136753, 13.80518863, 10.60837508, 12.21931616],
       [11.66837164, 17.47039537,  8.97420868, 11.56533851,  5.7295213 ],
       ...,
       [ 9.9971008 , 18.13280508, 17.41275096, 14.99774744,  7.15303818],
       [ 9.53328679,  6.05434569, 11.01390011, 13.53464124, 13.65750743],
       [15.54076189, 12.90572447, 12.81896665,  2.90401069,  9.23462747]])

#### Method 1: Using for-loops (bad!)

In [51]:
X_ = []

for col in X.T:
    col_mean = col.mean()
    col_std_dev = col.std()
    col_standardized = []
    for elem in col:
        elem_standardized = (elem - col_mean) / col_std_dev
        col_standardized.append(elem_standardized)
    X_.append(col_standardized)
    
X_ = np.array(X_).T

In [52]:
X_.mean(axis=0)

array([-1.52919455e-16,  7.49484919e-16, -2.20587992e-16,  6.00337557e-16,
        1.18929933e-15])

In [53]:
X_.std(axis=0)

array([1., 1., 1., 1., 1.])

#### Method 2: Vectorized (good!)

In [54]:
means = X.mean(axis=0)
std_devs = X.std(axis=0)
X_ = (X - means) / std_devs

In [55]:
X_.mean(axis=0)

array([-8.69544214e-16,  2.63216080e-14,  1.47286264e-14,  1.02035245e-14,
        5.95118000e-14])

In [56]:
X_.std(axis=0)

array([1., 1., 1., 1., 1.])

### Example 2: Calculating distances

Consider a matrix $X$ in which each row is a data point. Compute a vector of distances $d$ between a query point $q$ and each row in $X$.

In [57]:
X = np.random.normal(loc=10, scale=5, size=(1000000, 5))

print(X.shape)
print("X:", X)

q = np.random.normal(loc=10, scale=5, size=(5))
print()
print("q:", q)

(1000000, 5)
X: [[16.35577994 18.21976161  7.22089774  7.02746228  9.70531142]
 [15.11751176  9.33139481  4.90321699 14.79060652  6.82461619]
 [16.39816041  6.39261641 11.1098338   6.9681681  22.77355086]
 ...
 [ 2.99427944 15.64614365 15.80699962 12.4209975  16.79674743]
 [12.95105478 12.33807913  0.27642579  8.28007395  6.29905234]
 [12.31721264  4.40982302  6.16580666 13.03820627 13.75204579]]

q: [12.61239285 15.29941374  7.98994642  8.94104771  9.13684929]


#### Method 1: Using for-loops (bad!)

This code works, but it's ugly and takes a long time to run.

In [58]:
d = []

for x in X:
    sum_squared_diffs = 0
    for i in range(5):
        squared_diff = (x[i] - q[i]) ** 2
        sum_squared_diffs += squared_diff
    distance_x_to_q = sum_squared_diffs ** (1/2)
    d.append(distance_x_to_q)

d = np.array(d)
print(d.shape)
d

(1000000,)


array([ 5.20747279,  9.5385811 , 17.12450454, ..., 14.98394935,
        8.76770055, 12.65245234])

#### Method 2: Vectorized (good!)

Write vectorized code that's clean and fast!

In [60]:
### Your turn!